# Generated by Django 5.0.6 on 2024-11-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coupon",
            old_name="discount_amount",
            new_name="discount_value",
        ),
        migrations.AddField(
            model_name="coupon",
            name="used_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
