# Generated by Django 5.0.6 on 2024-12-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0002_rename_discount_amount_coupon_discount_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("flat", "Flat Amount")],
                default="percentage",
                max_length=10,
            ),
        ),
    ]
