# Generated by Django 5.0.6 on 2024-12-01 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0003_coupon_discount_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="discount_type",
        ),
    ]
