"""
Django settings for prokit project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-2u($0e8=q%hfyu8f53jz0y+qpog8of8k-aey5f=(&h0*r=lgvk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    'django.contrib.sites',  # Required by allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    "users",
    "admin_panel",
    "products",
    "categories",
    "order_management",
    "cart",
    "address",
    "coupon",
    "wishlist",
    "wallet",

]


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
    }
}


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "admin_panel.middleware.RedirectMiddleware",
    "users.middleware.RedirectHomeMiddleware",

]

ROOT_URLCONF = "prokit.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "context_processors.global_data",
            ],
        },
    },
]

WSGI_APPLICATION = "prokit.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        'NAME': 'prokit',     # Replace with your PostgreSQL database name
        'USER': 'postgres',     # Your PostgreSQL username
        'PASSWORD': 'passroot',  # Your PostgreSQL password
        'HOST': 'localhost',          # Set to 'localhost' or your server's address
        'PORT': '5432', 
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]



# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

# STATIC_URL = "static/"
import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
from decouple import config
#smtp configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP Server
EMAIL_PORT = 587  # TLS Port
EMAIL_USE_TLS = True  # Use TLS
EMAIL_HOST_USER = 'muhammedrashidn881@gmail.com'
EMAIL_HOST_PASSWORD = 'mpxl lfss cqih qiqc'  # Use App Password
DEFAULT_FROM_EMAIL = 'muhammedrashidn881@gmail.com'
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8000')


#authenticaton backends
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',            # Default backend
    'allauth.account.auth_backends.AuthenticationBackend',  # allauth backend
)

SITE_ID = 1 
# Automatically generate a username if not provided
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_SIGNUP_FORM_CLASS = None
SOCIALACCOUNT_AUTO_SIGNUP = True

# Ensure email is mandatory
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True   

LOGIN_REDIRECT_URL = '/home/'            # redirect after login
LOGOUT_REDIRECT_URL = '/signin/'           #redirect after logout

GOOGLE_CLIENT_ID = "277240722903-s5rfpo709qh4ej7makm8rti26f8vei66.apps.googleusercontent.com"
GOOGLE_REDIRECT_URI = 'http://127.0.0.1:8000/accounts/google/login/callback/'


SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_QUERY_EMAIL = True

RAZORPAY_KEY_ID = 'rzp_test_F6HvgkhI98quBC'
RAZORPAY_SECRET_KEY = 'TmxdDAIWatCEugQgdfJog5pC'