# Generated by Django 5.0.6 on 2024-12-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coupon", "0004_remove_coupon_discount_type"),
        ("order_management", "0002_alter_order_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coupon.coupon",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
