# Generated by Django 5.0.6 on 2024-12-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0004_order_sub_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_charge",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
