# Generated by Django 5.0.6 on 2024-12-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0008_alter_order_payment_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="coupon",
        ),
    ]
