# Generated by Django 5.0.6 on 2024-12-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0009_remove_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitems",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Requested To Return"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
