# Generated by Django 5.0.6 on 2024-12-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order_management", "0010_orderitems_item_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitems",
            name="item_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Requested To Return"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
