# Generated by Django 5.0.6 on 2024-12-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0011_alter_orderitems_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
