# Generated by Django 5.0.6 on 2024-10-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
