# Generated by Django 5.0.6 on 2024-12-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_brand_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="offer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
