# Generated by Django 5.0.6 on 2024-11-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="address",
            name="last_name",
        ),
    ]
