# Generated by Django 5.0.6 on 2024-11-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_remove_address_first_name_remove_address_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
