# Generated by Django 5.0.6 on 2024-11-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0005_address_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
