# Generated by Django 5.0.6 on 2024-12-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_address_address_type_alter_address_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
