# Generated by Django 5.0.6 on 2024-12-04 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cart_applied_coupon_and_more"),
        ("coupon", "0004_remove_coupon_discount_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coupon.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
