# Generated by Django 5.0.6 on 2024-10-28 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=3)),
                ("color", models.CharField(max_length=50)),
                ("image1", models.ImageField(upload_to="product_variants/")),
                ("image2", models.ImageField(upload_to="product_variants/")),
                ("image3", models.ImageField(upload_to="product_variants/")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
