# Generated by Django 5.0.6 on 2024-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_is_listed_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="variant",
            name="stock",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
