# Generated by Django 5.0.6 on 2024-11-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_variant_options_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="image1",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="image2",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="image3",
        ),
        migrations.AlterField(
            model_name="variant",
            name="size",
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name="VariantImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="product_variants/")),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "variant",
                "verbose_name_plural": "variants",
            },
        ),
    ]
