# Generated by Django 5.0.6 on 2024-11-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_remove_variant_image1_remove_variant_image2_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variantimages",
            options={"verbose_name": "image", "verbose_name_plural": "images"},
        ),
    ]
