# Generated by Django 5.0.6 on 2024-11-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
