# Generated by Django 5.0.6 on 2024-11-12 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_variant_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="slug",
        ),
    ]
