# Generated by Django 5.0.6 on 2024-11-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
