# Generated by Django 5.0.6 on 2024-11-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_alter_review_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="size",
        ),
        migrations.CreateModel(
            name="VariantSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=50)),
                ("stock", models.PositiveIntegerField()),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="products.variant",
                    ),
                ),
            ],
        ),
    ]
