# Generated by Django 5.0.6 on 2024-11-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_variant_size_variantsize"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variant",
            name="stock",
        ),
    ]
