# Generated by Django 5.0.6 on 2024-11-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_remove_variantsize_is_listed_alter_product_is_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_listed",
            field=models.BooleanField(default=True),
        ),
    ]
