# Generated by Django 5.0.6 on 2024-12-17 06:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_variant_is_listed_alter_product_is_listed"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
