# Generated by Django 5.0.6 on 2024-12-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
