# Generated by Django 5.0.6 on 2024-12-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_variantsize_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsize',
            name='stock',
            field=models.PositiveIntegerField(),
        ),
    ]
